image=binary-builder:
    image: cescoferraro/power
    tags: ["builder"]
    context: .
    dockerfile: docker/Dockerfile.build

job=binary:
    use: binary-builder
    artifact: ./dist/bin/
    mounts: [source, dist]
    command: docker/script/build
    env:
      - "POWER_JWT={env.POWER_JWT:}"
    description: "Build the ARM static binary"


image=release:
    image: cescoferraro/power
    tags: ["arm"]
    context: .
    dockerfile: docker/Dockerfile.release
    depends: [binary]
