image=binary-builder:
    image: cescoferraro/power
    tags: ["builder"]
    context: .
    dockerfile: docker/files/Dockerfile.build

job=binary:
    use: binary-builder
    artifact: ./dist/bin/
    mounts: [source, dist]
    command: docker/script/build.sh
    env:
      - "POWER_JWT={env.POWER_JWT:}"
      - "VERSION={env.VERSION:}"
    description: "Build the ARM static binary"
