image=armv7:
    image: cescoferraro/power
    tags: ["armv7-{env.VERSION:}","armv7"]
    context: .
    dockerfile: docker/files/Dockerfile.armv7.release
    depends: [binary]

image=armv6:
    image: cescoferraro/power
    tags: ["armv6-{env.VERSION:}","armv6"]
    context: .
    dockerfile: docker/files/Dockerfile.armv6.release
    depends: [binary]

image=amd64:
    image: cescoferraro/power
    tags: ["amd-{env.VERSION:}","amd"]
    context: .
    dockerfile: docker/files/Dockerfile.amd.release
    depends: [binary]

job=clean:
    use: binary-builder
    mounts: [source]
    command: rm -rf dist

alias=release:
    tasks: ["armv6:push", "armv7:push", "amd64:push", "clean"]
    description: "Run all tests"

